#!/bin/bash
osascript -e 'display notification "Installing X apps, go grab a ☕️" with title "Installer"
try
  do shell script "{{.InstallScript}}"
  display notification "Finished, yey!" with title "Installer"
on error
  display notification "Finished! There might have been some issues." with title "Installer"
end try'
