#!/bin/bash
osascript -e "display notification \"Installing X apps, go grab a ☕️\" with title \"Installer\""
osascript -e "do shell script \"bash $(pwd)/Contents/MacOS/run\" with administrator privileges"
